USE actors;

-- 1. Laura Bailey: 5.000.000 -> 6.600.000
UPDATE actores SET patrimonio_estimado = 6600000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 2. Troy Baker: 6.000.000 -> 7.920.000
UPDATE actores SET patrimonio_estimado = 7920000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 3. Mario Castañeda: 3.500.000 -> 4.620.000
UPDATE actores SET patrimonio_estimado = 4620000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 4. Rene Garcia: 2.800.000 -> 3.696.000
UPDATE actores SET patrimonio_estimado = 3696000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a44, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 5. Rie Takahashi: 2.000.000 -> 2.640.000
UPDATE actores SET patrimonio_estimado = 2640000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a55, 'principal', 3, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 6. Mamoru Miyano: 4.500.000 -> 5.940.000
UPDATE actores SET patrimonio_estimado = 5940000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a66;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a66, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 7. Tara Strong: 10.000.000 -> 13.200.000
UPDATE actores SET patrimonio_estimado = 13200000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a77;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a77, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 8. Cristina Hernandez: 1.800.000 -> 2.376.000
UPDATE actores SET patrimonio_estimado = 2376000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a88;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a88, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 9. Takehito Koyasu: 3.000.000 -> 3.960.000
UPDATE actores SET patrimonio_estimado = 3960000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a99;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a99, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 10. Nolan North: 4.000.000 -> 5.280.000
UPDATE actores SET patrimonio_estimado = 5280000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380baa;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380baa, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 11. Humberto Velez: 2.200.000 -> 2.904.000
UPDATE actores SET patrimonio_estimado = 2904000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bbb;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bbb, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 12. Yuri Lowenthal: 3.200.000 -> 4.224.000
UPDATE actores SET patrimonio_estimado = 4224000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bcc;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bcc, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 13. Kana Hanazawa: 5.000.000 -> 6.600.000
UPDATE actores SET patrimonio_estimado = 6600000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bdd;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bdd, 'principal', 3, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 14. Grey DeLisle: 5.000.000 -> 6.600.000
UPDATE actores SET patrimonio_estimado = 6600000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bee;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bee, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 15. Romina Marroquin: 1.200.000 -> 1.584.000
UPDATE actores SET patrimonio_estimado = 1584000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bff;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380bff, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 16. Yuki Kaji: 4.100.000 -> 5.412.000
UPDATE actores SET patrimonio_estimado = 5412000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c11, 'principal', 3, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 17. Jennifer Hale: 2.500.000 -> 3.300.000
UPDATE actores SET patrimonio_estimado = 3300000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c22;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c22, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 18. Isabel Martinon: 1.500.000 -> 1.980.000
UPDATE actores SET patrimonio_estimado = 1980000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c33;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c33, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 19. Tomokazu Sugita: 3.800.000 -> 5.016.000
UPDATE actores SET patrimonio_estimado = 5016000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c44;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c44, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);


-- 20. Steve Blum: 4.800.000 -> 6.336.000
UPDATE actores SET patrimonio_estimado = 6336000.0
WHERE id = a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c55;

INSERT INTO personajes_por_actor
(actor_id, rol, apariciones, nombre_personaje, produccion, tipo_produccion, generos)
VALUES
(a0eebc99-9c0b-4ef8-bb6d-6bb9bd380c55, 'secundario', 1, 'Sansa', 'Sansa Ball Race', 'profesional', ['Animacion', 'Carreras']);